//_________________________________________USER ENDPOINTS______________________________________//

//_________________________________________USER ENDPOINTS______________________________________//

//1 - Signup
//Its possible define users roles if wanted => "role":"admin". This information is optional and if none value was give by body, user will assume "normal" as role.

POST http://localhost:3003/users/signup
Content-Type: application/json

{
   "name": "Aversin", 
   "email": "aversin@email.com",
   "password": "123456",
   "role":"admin"
   
}

###

// 2 - Login

POST http://localhost:3003/users/login
Content-Type: application/json

{
   "email": "aversin@email.com", 
   "password": "123456"
}

###

// 3 Get all users - requires admin authorization
GET http://localhost:3003/users/allUsers
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NDg4ZmIzLTZkZGYtNDk1Yi05NGYxLTEzMDIxNzU4MmJjNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MzM2NTk5MiwiZXhwIjoxNjYzMzg3NTkyfQ.dsZKCjXSF6G8Cprp755g7vOqjC8ZD2bntKlfWqNKDfU
###

