  
  //1 - GET ALL USERS

GET     http://localhost:3003/users/all
###

// 2 - CREATE NEW USER

POST http://localhost:3003/users/create
Content-Type: application/json

{
    "name": "liliane aparecida",
    "email": "lilianeap@email.com",
    "password": "liliane"
}

####

  
  //1 - make POSTS

POST http://localhost:3003/posts/create
Content-Type: application/json

{
    "photo": "liliane.jpg",
    "description": "trabalhando na em acácia",
    "type": "normal",
    "author_id":"36fa5aaa-8697-4b69-a2e6-32abc2a4e78c"
}
###

  //1 - GET ALL POSTS

GET     http://localhost:3003/posts/all
###




  //1 - make friends

POST http://localhost:3003/friendship/3/makeFriend
Content-Type: application/json

{
    "reciever": "5a7e728a-3afa-47d6-850d-0fba7786e6a7"
}
###

  //1 - GET ALL FRIENDSHIP

GET     http://localhost:3003/friendship/all
###