//_________________________________________USER ENDPOINTS______________________________________//

  //1 - GET ALL USERS

GET     http://localhost:3003/users/all
###

  // 2 - CREATE NEW USER

POST http://localhost:3003/users/create
Content-Type: application/json

{
    "name": "liliane aparecida",
    "email": "lilianeap@email.com",
    "password": "liliane"
}

####
//_________________________________________POST ENDPOINTS______________________________________//

  
  //1 - MAKE A POST

POST http://localhost:3003/posts/create
Content-Type: application/json

{
    "photo": "tokenEterno.jpg",
    "description": "trabalhando na em acácia",
    "type": "normal",
    "author_id":"1"
}
###

  //2 - GET ALL POSTS

GET     http://localhost:3003/posts/all
###

  //2.1 - GET POST BY ID

GET     http://localhost:3003/posts/2/getPosts
###

//_________________________________________FRIENDSHIP ENDPOINTS______________________________________//
 
  //1 - MAKE FRIEND

POST http://localhost:3003/friendship/3/makeFriend
Content-Type: application/json

{
    "reciever": "1b845778-e2c5-4f8c-8baf-c68557991db4"
}
###

  //2 - GET ALL FRIENDSHIP

GET http://localhost:3003/friendship/all
###

  //3 - DELETE FRIENDSHIP

DELETE  http://localhost:3003/friendship/deleteFriend
Content-Type: application/json

{
    "idRequest": "5"
}
###