//_________________________________________USER ENDPOINTS______________________________________//

  //1 - GET ALL USERS

GET     http://localhost:3003/users/all
###

  // 2 - CREATE NEW USER

POST http://localhost:3003/users/create
Content-Type: application/json

{
    "name": "234236asd",
    "email": "sasda234242asdp@gmail.com",
    "password": "123"
}


###


//_________________________________________RECIPES ENDPOINTS______________________________________//

  //1 - GET ALL RECIPES

GET     http://localhost:3003/recipes/all
###

  // 2 - CREATE NEW RECIPE

POST http://localhost:3003/recipes/create
Content-Type: application/json

{
    "title": "Macarrão com salsicha",
    "description": "o bom e velho clássico do pobre",
    "instructions": "macarrão, salsicha, molho e ja era",
    "author_id": "1"
}
