////USERS ENDPOINTS

//1 - GET ALL USERS

GET     http://localhost:3003/users 
###

//2 - CREATE NEW USER

POST    http://localhost:3003/users
Content-Type: application/json

{
    "name": "Stand By Me",
    "email": "nobodyknows@hotmail.com",
    "password": "the way is gonna be"
}
###
////PRODUCTS ENDPOINTS

//1 - GET ALL PRODUCTS

GET     http://localhost:3003/products 
###

//2 - CREATE NEW PRODUCT
POST    http://localhost:3003/products
Content-Type: application/json

{
    "name": "Joystick Futurista",
    "price": 500.00,
    "img_url": "https://images.hdqwalls.com/wallpapers/playstation-joystick.jpg"
}
###

////PURCHASE ENDPOINTS

//2 - CREATE NEW PURCHASE
POST    http://localhost:3003/purchases
Content-Type: application/json

{
    "user_id": "4d3bc362-f838-43d6-9e06-5f3883873f74",
    "products_id": 1,
    "quantity": 2
}
###
